name: mentors_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Formular
      fonts:
        - asset: assets/fonts/Formular.ttf
          weight: 300            
        - asset: assets/fonts/Formular-Medium.ttf
          weight: 500
    - family: Poligon
      fonts:
        - asset: assets/fonts/Poligon-Light.otf
          weight: 300
        - asset: assets/fonts/Poligon-Thin.otf
          weight: 200
        - asset: assets/fonts/Poligon-Medium.otf
          weight: 600
    - family: PP Monument Extended
      fonts:
        - asset: assets/fonts/PPMonumentExtended-Regular.otf
          weight: 400
        - asset: assets/fonts/PPMonumentExtended-Light.otf
          weight: 300
        - asset: assets/fonts/PPMonumentExtended-Black.otf
          weight: 900
    - family: Monument Extended
      fonts:
        - asset: assets/fonts/MonumentExtended-Regular.otf
        - asset: assets/fonts/MonumentExtended-UltraBold.otf
          weight: 900